### ISSUE TITLE
Parent parser doesn't show it's arguments on GUI

### ISSUE THREAD

**Issue by acrobotache** [chriskiehl/GooeyExamples#20]
Issue in the following python Script: https://github.com/chriskiehl/GooeyExamples/blob/master/examples/subparser_demo.py

```
    parser = GooeyParser(description=settings_msg)
    parser.add_argument('--verbose', help='be verbose', dest='verbose',
                        action='store_true', default=False)
    subs = parser.add_subparsers(help='commands', dest='command')
```
--verbose arguments is not visible on output screen. What can we do for making it visible on GUI?
![bug](https://user-images.githubusercontent.com/26625338/66562457-54ee8a00-eb79-11e9-8ff6-30b8f5186745.PNG)

**Comment by chriskiehl** [comment]
This isn't something currently supported by Gooey. It's on the roadmap, though. Originally, it was a OX question of _how_ to display parent arguments in the UI, but since the introduction of tabs, there's a clear path forward on the UX front.
