### ISSUE TITLE
subparser_demo.py example issues ValueError when run

### ISSUE THREAD

**Issue by Krotera** [chriskiehl/GooeyExamples#23]
@ [line 33](https://github.com/chriskiehl/GooeyExamples/blob/master/examples/subparser_demo.py#L33):
```
Traceback (most recent call last):
  File "subparser_demo.py", line 95, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/gooey/python_bindings/gooey_decorator.py", line 87, in inner2
    return payload(*args, **kwargs)
  File "subparser_demo.py", line 33, in main
    curl_parser.add_argument('--dump-header', type=argparse.FileType,
  File "/usr/lib/python3.8/site-packages/gooey/python_bindings/gooey_parser.py", line 88, in add_argument
    self.parser.add_argument(*args, **kwargs)
  File "/usr/lib/python3.8/argparse.py", line 1376, in add_argument
    raise ValueError('%r is a FileType class object, instance of it'
ValueError: <class 'argparse.FileType'> is a FileType class object, instance of it must be passed
```
The line is:
```Python
curl_parser.add_argument('--dump-header', type=argparse.FileType,
                             help='Write the protocol headers to the specified file')
```
Ditto for similar line 64.

**OS:** Linux (Manjaro 18.1.4)
**Python version:** 3.8.0
**Gooey version:** 1.0.3

**Comment by MrSassyBritches** [comment]
This resolved the error for me and the other line that come up.

`curl_parser.add_argument('--dump-header', type=argparse.FileType,
                             help='Write the protocol headers to the specified file')`

**Comment by Krotera** [comment]
> This resolved the error for me and the other line that came up.
> 
> ```python
> curl_parser.add_argument('--dump-header', 
>                           type=argparse.FileType(),
>                           help='Write the protocol headers to the specified file')
> ```

Yep! Changing `argparse.FileType` to `argparse.FileType()` in both lines fixes it here too.

**Comment by chriskiehl** [comment]
Fix has been merged :+1:
