### ISSUE TITLE
no module name wx

### ISSUE THREAD

**Issue by mlane706** [chriskiehl/GooeyExamples#3]
I'm getting the following errors when I run simple_demo.py

> > > import simple_demo.py
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "simple_demo.py", line 7, in <module>
> > >     from gooey import Gooey, GooeyParser
> > >   File "gooey/**init**.py", line 2, in <module>
> > >     from gooey.python_bindings.gooey_decorator import Gooey
> > >   File "gooey/python_bindings/gooey_decorator.py", line 14, in <module>
> > >     from gooey.gui import application
> > >   File "gooey/gui/application.py", line 5, in <module>
> > >     import wx
> > > ImportError: No module named wx

Any recommendations?

**Comment by jjconti** [comment]
You have to install wxPython in your system. In MacOS:

```
brew install wxmac
brew install wxpython
```

**Comment by chriskiehl** [comment]
Dependency installation instructions have been added to the README.
